/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    public boolean someLibraryMethod() {
        int h = 10;
        int n = someNumber();
        return h > n;
    }

    private int someNumber() {
        return 100;
    }
}
