/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;

public class App {

    public static void main(String[] args) {
        FileManager fm = new FileManager();
        String dir = "./";

        for (File file : fm.listFiles(dir)) {
            System.out.println(file.getPath());
        }
    }
}
